#!/bin/bash
#
# $Id: kurenmac 28 2016-08-09 17:03:45+04:00 toor $
#
_bashlyk=kurenma . bashlyk
#
#
#
shopt -s expand_aliases
alias try="udfTry <<-catch.e"

udfTry() {

    local s b=true fn i=0
    #
    udfMakeTemp fn
    #
    while read s; do

	i=$((i+1))

	[[ -n "$s" ]] || continue

	eval "$s" > $fn 2>&1 && echo -n "." || {

		_ iTryBlockLine $i
		b=false
		break
	}

    done

    if ! $b; then

	echo "?"
	udfStackTrace $s
	eval $( udfOnError exitwarn $i "line: $i, code: $s, output: $(< $fn)" )

    fi

}
#
udfGetValidIPsOnly() {

	[[ -n "$*" ]] || eval $( udfOnError return iErrorEmptyOrMissingArgument )

	local s sDig sOut

	for s in $*; do

		[[ $s =~ ^[0-9.]+$ ]] && ipcalc "$s" | grep '^INVALID ADDRESS:' && continue
		sipcalc -d4 "$s" | grep '^-\[ERR :' && continue
		sDig=$( dig +short $s | xargs )
		[[ -n "$sDig" ]] && s="$sDig"
		sOut+="$s "

	done >/dev/null 2>&1

	echo ${sOut% *} | tr ' ' '\n' | sort | uniq | xargs

	return 0

}
#
udfMain() {

	[[ $UID == 0 ]] || eval $( udfOnError throw  iErrorNotPermitted "You must be root to run this." )

	local a cnClient cnServer dev fn fnAns fnClientCrt fnClientKey fnKey fnPub fnServerCrt host i ini ipClient ipServer keepalive pathCrt pathIni pathKey peer port s

	DEBUGLEVEL=4

	udfThrowOnCommandNotFound echo ip ipcalc dig grep knock openssl ping printf sed sipcalc tee wg

	pathIni=$( _ pathIni )
	ini=${pathIni}/client.kurenma.ini
	pathCrt=${pathIni}/ssl/public
	pathKey=${pathIni}/ssl/private

	udfIni $ini ':dev;host;port;keepalive ssl:cnServer;cnClient'

	: ${dev:=wg0}
	: ${i:=256}

	if udfIsNumber $keepalive; then

		(( $keepalive >= 10   )) || keepalive=10
		(( $keepalive <= 3600 )) || keepalive=3600

	else

		keepalive=0

	fi

	udfDebug 2 "configuration:" && udfShowVariable dev host port cnServer cnClient keepalive
	udfThrowOnEmptyVariable cnClient cnServer dev host pathIni port

	fnServerCrt=${pathCrt}/${cnServer}.crt
	fnClientCrt=${pathCrt}/${cnClient}.crt
	fnClientKey=${pathKey}/${cnClient}.key

	s=$( grep Subject: $fnClientCrt | sed -re "s/.*CN=(.*)\/email.*/\1/" )

	if [[ $s != $cnClient ]]; then

		eval $( udfOnError throw iErrorNotValidArgument "invalid cert file $fnClientCrt" )

	fi

	if [[ -f $fnClientCrt && -f $fnClientKey  && -f $fnServerCrt ]]; then


		udfDebug 3 && printf "client auth info:\n\tremote public key\t- %s\n\tlocal private key\t- %s\n\tlocal Common Name \t- %s\n" "$fnServerCrt" "$fnClientKey" "$cnClient"

	else

		eval $( udfOnError throw iErrorNoSuchFileOrDir "$fnClientCrt and/or $fnClientKey and/or $fnServerCrt" )

	fi

	udfMakeTemp fnKey
	udfMakeTemp fnPub
	udfMakeTemp fnAns

	while true; do

		s=$( grep keyid $fnServerCrt | sed -r -e "s/^.*keyid:(..):(..):(..):(..):(..):(..):.*$/0x\1\2 0x\3\4 0x\5\6/" )

		[[ -n "$s" ]] || eval $( udfOnError throw "iErrorEmptyOrMissingArgument" "$fnServerCrt - not valid format" )
		udfDebug 5 "server crt keyid head: $s"

		s=$( printf "%d %d %d" $s ) || eval $( udfOnError throw "iErrorNotValidArgument" "$fnServerCrt - not valid format" )

		udfDebug 5 "knock  ports sequence: $s"

		udfDebug 2 "check server availibity:"

		while true; do

			if echo "${i}%8" | bc | grep '^0$' >/dev/null; then

				knock $host $s && echo -n "!"

			fi
			sleep 1

			nc -w 3 -z ${host} ${port} 2>/dev/null && break
			echo -n "."
			i=$((i-1))

			if (( $i <= 0 )); then

				eval $( udfOnError warn iErrorNotPermitted "${host}:${port} are unreacheable" )
				i=256
			fi

		done
		udfDebug 2 "ok."
		sleep 4

		s="$( wg genkey | tee $fnKey | wg pubkey | tee $fnPub | udfEcho - $cnClient | openssl smime -encrypt -aes256 -outform PEM $fnServerCrt | nc -w 24 -i 4 $host $port | tee $fnAns | openssl smime -decrypt -inform PEM -inkey $fnClientKey | tr -d '\r' )"

		udfDebug 4 && \
		printf "\nclient wirequard keys:\n\tprivate\t- %s\n\tpublic\t- %s\n\n" \
			"$(head -c 10 $fnKey)<skipped>" "$(head -c 10 $fnPub)<skipped>"

		[[ $s =~ ^OK: ]] && break

		[[ -z "$s" ]] && s="$(< $fnAns)"

		eval $( udfOnError warn iErrorNotValidArgument "malformed answer from ${host}:${port} $s" )

		sleep 8

	done

	rm -f $fnPub

	a=( ${s//:/ } )

	peer=$( echo ${a[1]} | grep -P "^[a-zA-Z0-9+/]+={0,2}$" )
	udfIsNumber ${a[2]} && port=${a[2]} || port=''
	ipClient=$( udfGetValidIPsOnly ${a[3]} )
	ipServer=$( udfGetValidIPsOnly ${a[4]} )

	udfDebug 3 && \
		printf "server connection properties:\n\tleased ip: %s\n\t   server: %s\n\t     peer: %s\n\t     port: %s\n\n" \
			"$ipClient" "$ipServer" "${peer:0:10}<skipped>" "$port"

	udfThrowOnEmptyVariable peer port ipClient ipServer

	udfDebug 0 && \
		echo -n "Setup tunnel for peer ${peer:0:10}<skipped> with IP $ipClient to ${host}:${port}: "
	#
	try

		ip link del dev $dev || true
		ip link add dev $dev type wireguard
		wg set $dev private-key $fnKey \
			peer $peer \
			allowed-ips 0.0.0.0/0 \
			persistent-keepalive $keepalive \
			endpoint "${host}:${port}"

		rm -f $fnKey
		ip address add "${ipClient}"/24 dev $dev
		ip link set up dev $dev

	catch.e

	ping -t 1 -c 3 -q $ipServer >/dev/null 2>&1
	echo "ok."

	eval set -- $(_ sArg)

	if [[ "$1" == "default-route" ]]; then

		host="$(wg show $dev endpoints | sed -n 's/.*\t\(.*\):.*/\1/p')"
		udfDebug 3 "host for route to wg = $host"
		udfDebug 3 "route info for ${host}:"
		ip route get $host
		host="$( ip route get $host | sed '/ via [0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/{s/^\(.* via [0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\).*/\1/}' | head -n 1 )"
		udfDebug 3 "new route $host"
		ip route add $host 2>/dev/null || true
		ip route add 0/1 dev $dev
		ip route add 128/1 dev $dev

	fi

	udfDebug 1 && printf "\nclient configuration done.\n"

	udfDebug 3 && {

		printf "\n\nWireguard interface %s info:\n-----------------------------\n\n" "$dev"

		wg show $dev | sed -re "s/(peer:|public.?key[ :]|private.?key[ :]).*$/\1 <hidden>/ig"

		ip addr show $dev | grep inet

		printf "\n----\n"

	} >&2

	wg showconf $dev > ${pathIni}/${cnClient}_${cnServer}.${dev}.conf
	chmod 0600 ${pathIni}/${cnClient}_${cnServer}.${dev}.conf

}
#
#
#
udfMain
#
