#!/bin/bash
#
# $Id: kurenmas 63 2016-09-13 11:51:56+04:00 toor $"
#
_kurenmas_sVersion=0.3
#
_bashlyk=kurenma . bashlyk
#
#
#
_bashlyk_iErrorTimeExpired=167
_bashlyk_hError[$_bashlyk_iErrorTimeExpired]="time expired"
_bashlyk_iErrorNotAvailable=166
_bashlyk_hError[$_bashlyk_iErrorNotAvailable]="target is not available"
_bashlyk_iErrorInvalidArgument=253
_bashlyk_hError[$_bashlyk_iErrorInvalidArgument]="invalid argument"
_bashlyk_iErrorInvalidVariable=200
_bashlyk_hError[$_bashlyk_iErrorInvalidVariable]="invalid variable"

#****m* kurenma/kurenmas
#  DESCRIPTION
#    kurenmas - Kurenma Service for WireGuard tunnels
#  AUTHOR
#    Damir Sh. Yakupov <yds@bk.ru>
#******
#
udfWatchdog() {

	udfOn EmptyOrMissingArgument throw "$1"
	udfIsNumber $2 || eval $( udfOnError2 throw iErrorNonValidArgument "$2" )

	local i=0

	while true; do

		i=$((i+1))

		if [[ -s $1 && $( tail -n 1 $1 ) == "stop" ]]; then

			i=$(_ iErrorAbortedBySignal)
			break

		fi

		sleep 1

		if (( i >= $2 )); then

			i=0
			break

		fi

	done

	return $i
}
#
udfMakeFifo() {

	[[ -n "$1" ]] || eval $( udfOnError iErrorEmptyOrMissingArgument )
	udfMakeTemp $1 path=$( _ pathRun )
	rm -f ${!1}
	mkfifo ${!1}

}
#
udfGetTimeInSec() {

	if [[ "$1" == "-v" ]]; then

		udfIsValidVariable "$2" || eval $( udfOnError2 iErrorNotValidArgument "$2 - variable name required" )

		[[ "$3" == "-v" ]] && eval $( udfOnError2 iErrorNotValidArgument "$3 - number with time suffix expected" )

		eval 'export $2="$( udfGetTimeInSec $3 )"'
		[[ -n ${!2} ]] || eval 'export $2="$( udfGetTimeInSec $4 )"'
		[[ -n ${!2} ]] || eval $( udfOnError2 iErrorEmptyResult "$2 - empty variable" )

		return $?

	fi

	local i=${1%%[[:alpha:]]*}

	udfIsNumber $i || eval $( udfOnError2 iErrorNotValidArgument "$i - number expected" )

	case ${1##*[[:digit:]]} in

		seconds|second|sec|s|'') echo $i;;
		   minutes|minute|min|m) echo $(( i*60 ));;
		        hours|hour|hr|h) echo $(( i*3600 ));;
		             days|day|d) echo $(( i*3600*24 ));;
		           weeks|week|w) echo $(( i*3600*24*7 ));;
		       months|month|mon) echo $(( i*3600*24*30 ));;
		           years|year|y) echo $(( i*3600*24*365 ));;
	                              *) echo ""
                                       eval $( udfOnError2 iErrorNotValidArgument "$1 - number with time suffix expected" )

	esac

    return $?

}
#
udfGetValidIPsOnly() {

	[[ -n "$*" ]] || eval $( udfOnError return iErrorEmptyOrMissingArgument )

	local s sDig sOut

	for s in $*; do

		[[ $s =~ ^[0-9.]+$ ]] && ipcalc "$s" | grep '^INVALID ADDRESS:' && continue
		sipcalc -d4 "$s" | grep '^-\[ERR :' && continue
		sDig=$( dig +short $s | xargs )
		[[ -n "$sDig" ]] && s="$sDig"
		sOut+="$s "

	done >/dev/null 2>&1

	echo ${sOut% *} | tr ' ' '\n' | sort | uniq | xargs

	[[ -n "${sOut% *}" ]] || eval $( udfOnError return iErrorEmptyResult )

	return 0

}
#
udfStopProcess() {

	local pid s

	if udfIsNumber $1; then

		pid=$1
		shift

	else

		pid="$( ps -C "$*" -o pid= | xargs )"

	fi

	for s in 15 9; do

		udfIsNumber $pid || continue

		sleep 1

		udfCheckStarted $pid $* && kill -${s} $pid


	done

	return 0

}
#
udfShowPeerInfo() {

	udfThrowOnEmptyVariable dev

	printf -- "\n\nWireGuard interface %s info:\n-----------------------------\n\n" "$dev"

	wg show $dev | sed -re "s/(peer:|public.?key[ :]|private.?key[ :]).*$/\1 <hidden>/ig"

	ip addr show $dev | grep inet

	printf -- "\n----\n"

}
#
udfSelfCheck() {

	udfThrowOnEmptyVariable fnCtl portAuth
	udfIsNumber $portAuth || eval $( udfOnError throw NotValidArgument "$portAuth" )

	local fn iA iB iC=0 s

	fn=$( _ fnLog )

	[[ -f $fn ]] || eval $( udfOnError throw iErrorNoSuchFileOrDir "$fn" )

	while true; do

		## TODO check peers expiring
		## TODO implement auto sleep mode

		udfWatchdog $fnCtl 15 || break

		iB=$( sed -rn "/.* Connection from .* port .* .* accepted .*/{=}" $fn | tail -n 1 )

		udfWatchdog $fnCtl 15 || break

		iA=$( sed -rn "/.* (Listening on .* .*|Connection closed, listening again.)/{=}" $fn | tail -n 1 )

		udfIsNumber "$iA" || iA=0
		udfIsNumber "$iB" || iB='-1'

		(( iA - iB > 0 )) && continue

		udfDebug 4 "selfcheck checkpoint - iA=$iA iB=$iB"

		if (( iA == iC )); then

			udfDebug 4 "maybe netcat is hung - iA=$iA iB=$iB - try restart.."
			udfStopProcess $cmdNetcat

		else

			(( iA == -1 )) && iC=0 || iC=$iA
			udfWatchdog $fnCtl 15 || break

		fi

	done

	return 0
}
#
udfWaitRequest() {

	local -r iMax=32
	local i=0 s csv
	#
	while read -n 66 s; do

		udfDebug 5 "input line ${i}: ${s:0:10}<skipped>"

		if [[ $s =~ ^-----BEGIN.PKCS7-----$ ]]; then

			csv=""
			i=0

		fi

		csv+="${s}:"
		i=$((i+1))

		if (( $i > $iMax )); then

			udfDebug 0 "Warn: too many lines received, ignore .."
			csv=""
			i=0

		fi

		if [[ $csv =~ ^-----BEGIN.PKCS7-----.*-----END.PKCS7-----:$ ]]; then

			udfDebug 5 "start request handling."
			udfHandleRequest "$csv"
			csv=""
			i=0

		fi

	done

}
#
udfHandleRequest() {

	udfThrowOnEmptyArgument "$@"
	udfThrowOnEmptyVariable fnServerKey ipClient ipServer dev pathCrt pathDat pathIni tsKeepalive tsPeerTimeout

	local a csvCIDR cnClient fn fnClientCrt fnLeased peer s

	udfMakeTemp fn

	printf -- "${1//:/\\n}" | openssl smime -decrypt -inform PEM -inkey $fnServerKey | tr -d '\r' > $fn

	udfDebug 5 && {

		printf -- "\nreceived data:\n--------------\n"
		head -n 2 $fn
		echo "$( tail -n +3 $fn | head -c 10 )<skipped>"
		echo "--------------"

	} >&2

	if [[ $( wc -l < $fn ) != 3 ]]; then

		echo "Error - unexpected format"
		eval $( udfOnError2 retwarn iErrorNotValidArgument "untrusted input data" )

	fi

	peer="$( tail -n +3 $fn )"
	s=$( head -n 1 $fn )
	rm -f $fn

	for fn in $( ls $pathCrt ); do

		if [[ -f ${pathCrt}/${fn} && $fn =~ .crt ]]; then

			cnClient="$( grep 'Subject:' ${pathCrt}/${fn} | sed -re "s/.*CN=(.*)\/email.*/\1/" )"

		else

			continue

		fi

		[[ $s == $cnClient ]] || continue

		fnClientCrt=${pathCrt}/${fn}
		break

	done

	if [[ -z "$fnClientCrt" ]]; then

		echo "Error - unexpected request"
		eval $( udfOnError2 retecho iErrorNotPermitted "client certificate not found" )

	fi

	fnLeased=${pathDat}/${cnServer}.${dev}.leased

	{

		udfDebug 4 && \
			printf -- "\nremote peer info:\n\tClient Common Name\t- %s\n\tPublic key for %s\t- %s\n" \
				"$cnClient" "$dev" "${peer:0:10}<skipped>" >&2

		if [[ $(wg show $dev | grep peer | wc -l) -ge 253 ]]; then

			wg set $dev peer $(wg show $dev latest-handshakes | sort -k 2 -b -n | head -n 1 | cut -f 1) remove

		fi

		for s in $( wg show $dev latest-handshakes | tr '\t' ':' | xargs ); do

			if udfIsNumber ${s##*:}; then

				udfDebug 4 "$(date +%s) - ${s##*:} > $tsPeerTimeout"
				(( ${s##*:} < 999 )) && continue
				## TODO update latest handshake for peer in $fnLeased
				if (( $(date +%s) - ${s##*:} >= tsPeerTimeout )); then

					wg set $dev peer ${s%%:*} remove
					udfDebug 4 "peer ${s:0:10}<skipped> removed .. $?"

				fi

			else

				eval $( udfOnError2 warn iErrorNotValidArgument "${s##*:}" )

			fi

		done

		if [[ "$ipClient" == "commonname" ]]; then

			ipClient=$( udfGetValidIPsOnly $cnClient )
			udfDebug 5 "Leased IP by CN to $cnClient - $ipClient"

		fi

		if [[ -z "$ipClient" || $ipClient == "dynamic" ]]; then

			[[ -f $fnLeased ]] || touch $fnLeased

			ipClient=$( grep -P "^${cnClient}:\S+$" $fnLeased | tail -n 1 | cut -f 2 -d':' | xargs )
			ipClient=$( udfGetValidIPsOnly $ipClient )

		fi

		if [[ -z "$ipClient" ]]; then

			ipClient=$( s="$( wg show $dev allowed-ips )"; for ((i=2; i<=254; i++)); do ip="${ipServer%.*}.$i"; [[ $s != *${ip}/32* ]] && echo $ip && break; done )
			ipClient=$( udfGetValidIPsOnly $ipClient )

		fi

		if [[ -z "$ipClient" ]]; then

			echo "not allocated IP to the client"
			eval $( udfOnError2 retecho iErrorEmptyOrMissingArgument "not allocated IP to the client" )

		fi

		csvCIDR="${ipClient}/32"

		for s in ${ipsAllowed//[;,]/ }; do

			[[ -n "$( udfGetValidIPsOnly ${s%/*} )" ]] || continue

			if [[ $s == ${s##*/} ]]; then

				s="$( udfGetValidIPsOnly ${s%/*} )"

			else

				udfIsNumber "${s##*/}" && (( "${s##*/}" > 33 )) && continue
				udfIsNumber "${s##*/}" || continue

			fi

			csvCIDR+=",$s"

		done

		udfDebug 5 "allowed-ips: $csvCIDR"

		udfMakeTemp fn
		if wg set $dev peer "$peer" allowed-ips "$csvCIDR" persistent-keepalive $tsKeepalive 2>$fn; then

			echo "OK:$( wg show $dev private-key | wg pubkey ):$( wg show $dev listen-port ):${ipClient}:${ipServer}"

			for s in $( wg show $dev peers ); do

				grep ":${s:0:10}$" $fnLeased

			done > $fn
			mv -f $fn $fnLeased
			echo "${cnClient}:${ipClient}:$(date +%s):${peer:0:10}" >> $fnLeased

		else

			echo "Error $(< $fn) $?"

		fi

	} | openssl smime -encrypt -outform PEM $fnClientCrt

	for s in $( wg show $dev allowed-ips | grep none | cut -f 1 | xargs ); do

		wg set $dev peer $s remove
		udfDebug 4 "${dev}: remove unused peer ${s:0:10}<skipped> .. $?"

	done

	udfDebug 1 "server configuration updated."
	udfDebug 5 && udfShowPeerInfo >&2

	wg showconf $dev > ${pathIni}/${cnServer}.${dev}.conf
	chmod 0600 ${pathIni}/${cnServer}.${dev}.conf

}
#
_defLocal() {

	local s S

	for s in ${*//[;,]/ }; do

		udfIsValidVariable $s || eval $( udfOnError throw iErrorNonValidVariable "$s" )
		S+="$s "

	done

	echo "local ${S% *}"

}
#
udfSetupTunnel() {

	udfThrowOnEmptyVariable dev ipServer port

	udfDebug 4 "Init WireGuard device $dev"

	try-every-line

		ip link del dev $dev 2>/dev/null || true
		ip link add dev $dev type wireguard
		ip address add ${ipServer}/24 dev $dev
		wg set $dev private-key <(wg genkey) listen-port $port
		ip link set up dev $dev

	catch-every-line

	udfDebug 4 "init new server pub key: $( wg show $dev private-key | wg pubkey | head -c 10 )<skipped>"

	return 0

}
#
udfMain() {

	DEBUGLEVEL=3

	udfThrowOnCommandNotFound cut dig echo grep ip ipcalc kill mkdir nc openssl ps sipcalc sort uniq wg xargs

	[[ $UID == 0 ]] || eval $( udfOnError throw NotPermitted "You must be root to run this." )

	local -a aId
	local cmdNetcat fn fnCtl fnServerKey fnTmp ini ip pathIni pathCrt pathDat pathKey pathRun s
	local csvSectionMain csvSectionSSL ipsAllowed

	aId=( $( grep -Po '\044Id\072 \S+ \d+ \S+ \S+ \S+ \044' $0 ) ) && udfDebug 1 "start role=$_KURENMA_SERVICE_ROLE $( _ s0 ) (с) ${aId[3]}, rev${aId[2]}"

	csvSectionMain='bDaemonize;bDefaultRoute;dev;host;ipServer;ipClient;port;portAuth;role;tsKeepalive;tsPeerTimeout'
	csvSectionSSL='cnClient;cnServer'
	eval $( _defLocal $csvSectionMain $csvSectionSSL )

	udfExitIfAlreadyStarted

	pathDat=$( _ pathDat )
	pathIni=$( _ pathIni )
	pathRun=$( _ pathRun )

	pathCrt=${pathIni}/ssl/public
	pathKey=${pathIni}/ssl/private
	ini=${pathIni}/kurenma.ini
	fnCtl=${pathRun}/kurenma.pid
	mkdir -p $pathDat || eval $( udfOnError retecho NotExistNotCreated $pathDat )

	udfIni $ini ":${csvSectionMain}" "ssl:${csvSectionSSL}" "ipsAllowed:="

	: ${dev:=wg0}
	: ${ipClient:=dynamic}
	: ${ipServer:=192.168.29.1}
	: ${port:=12912}
	: ${portAuth:=42912}
	: ${tsPeerTimeout:=12hours}

	cmdNetcat="nc -k -l -v $portAuth"

	udfIsNumber $tsKeepalive || tsKeepalive=0
	(( $tsKeepalive > 65355 )) && tsKeepalive=65355

	_bashlyk_sBehaviorOnError=return udfGetTimeInSec -v tsPeerTimeout $tsPeerTimeout "2day"

	udfDebug 2 && udfShowVariable dev port portAuth cnServer ipServer ipsAllowed tsKeepalive tsPeerTimeout
	udfThrowOnEmptyVariable cnServer dev ipServer pathCrt pathDat pathIni pathKey pathRun port portAuth tsPeerTimeout

	fnServerKey=${pathKey}/${cnServer}.key

	[[ -f $fnServerKey ]] || eval $(udfOnError exitecho NoSuchFileOrDir "$fnServerKey")

	if [[ -z "$( wg | grep $dev )" || -z "$( ip addr show $dev | grep $ipServer )" ]]; then

		udfSetupTunnel

	fi

	echo "start" > $fnCtl
	udfStopProcess $cmdNetcat
	udfSelfCheck &
	udfAddPid2Clean $!

	while true; do

		udfDebug 4 "Daemon for WireGuard clients (re)started.."
		udfMakeFifo fnTmp
		cat $fnTmp | udfWaitRequest | $cmdNetcat > $fnTmp
		udfWatchdog $fnCtl 1 || break
		rm -f $fnTmp

	done

	udfFinally "service down"

}
#
#
#
udfMain
#
