#!/bin/bash
#
# $Id: kurenma-knockd-setup 224 2018-08-20 01:27:25+04:00 yds $
#
_bashlyk=kurenma . bashlyk
#
#
#
#****h* command/kurenma-knockd-setup
#
#  DESCRIPTION
#
#    part of the kurenma(7) package, tool to configure the third-party
#    application. kurenma-knockd-setup  get knock-sequence  of port numbers from
#    the  server's X.509-certificate  and  write  the appropriate section of the
#    settings in the knockd.conf(5) configuration file. Only required for server
#    roles.
#
#  SEE ALSO
#
#    kurenma-firehol-update(8), knockd(1), kurenma-ssl-gen(8)
#
#******
kurenma-knockd-setup::main() {

  [[ $UID == 0 ]] || \
    error NotPermitted warn+exit -- You must be root to run this.

  pid::onStarted.exit

  exit+warn on CommandNotFound openssl sed

  local fnCA conf pathCfg s

  pathCfg=$( _ pathCfg )
  throw on EmptyVariable pathCfg

  conf="/etc/knockd.conf"
  #
  fnCA=${pathCfg}/ssl/public/cacert.pem

  [[ -s $fnCA ]] || error NoSuchFileOrDir throw -- $fnCA

  s=$(                                                                         \
    openssl x509 -sha1 -in $fnCA -noout -fingerprint | sed -r -e               \
    "s/^SHA1 Fing.*nt=(..):(..):(..):(..):(..):(..):.*$/0x\1\2 0x\3\4 0x\5\6/" \
  )

  err::debug 2 "CA cert fingerprint header: $s"
  s=$( printf -- "%d,%d,%d" $s )
  err::debug 2 "knock ports sequence: $s"

  CFG ini
  ini.settings.section.padding = false
  ini.settings chComment       = '#'

  ini.storage.use $conf
  ini.load

  ini.set [ kurenma ] sequence    = $s
  ini.set [ kurenma ] seq_timeout = 5
  ini.set [ kurenma ] command     = /usr/bin/kurenma-firehol-update %IP%
  ini.set [ kurenma ] tcpflags    = syn

  ini.save $conf
  err::debug 2 && ini.show | sed -re "s/^[[:space:]]/\xc2\xa0\x20/"
  ini.free

  if [[ -d /run/systemd/system ]]; then

    systemctl stop  knockd.service
    sleep 2
    systemctl start knockd.service


  else

    service knockd stop
    sleep 2
    service knockd start

  fi

  std::finally "service down"

}
#
#
#
kurenma-knockd-setup::main
#
