#!/bin/bash
#
# $Id: setup-knockd 171 2017-06-09 15:26:28+04:00 toor $
#
_bashlyk=kurenma . bashlyk
#
#
#
#****h* command/setup-knockd
#
#  DESCRIPTION
#
#    part of the kurenma(7) package, tool to configure the third-party
#    application.
#    setup-knockd get knock-sequence  of  port  numbers  from  the  server's
#    X.509-certificate  and write the appropriate section of the settings in
#    the knockd.conf(5) configuration file. Only required for server roles.
#
#  SEE ALSO
#
#    update-firehol(8), knockd(1), gen-ssl-kurenma(8)
#
#******
kurenma-setup-knockd::main() {

  [[ $UID == 0 ]] || on error warn+exit NotPermitted "You must be root to run this."

  pid::onStarted.exit

  exit+warn on CommandNotFound openssl sed

  local fnCA conf pathIni s

  pathIni=$( _ pathIni )
  throw on EmptyVariable pathIni

  conf="/etc/knockd.conf"
  #
  fnCA=${pathIni}/ssl/public/cacert.pem

  [[ -s $fnCA ]] || on error throw NoSuchFileOrDir $fnCA

  s=$(                                                                         \
    openssl x509 -sha1 -in $fnCA -noout -fingerprint | sed -r -e               \
    "s/^SHA1 Fing.*nt=(..):(..):(..):(..):(..):(..):.*$/0x\1\2 0x\3\4 0x\5\6/" \
  )

  err::debug 2 "CA cert fingerprint header: $s"
  s=$( printf -- "%d,%d,%d" $s )
  err::debug 2 "knock ports sequence: $s"

  INI ini
  ini.settings.section.padding = false
  ini.settings chComment       = '#'

  ini.load $conf

  ini.set [ kurenma ] sequence    = $s
  ini.set [ kurenma ] seq_timeout = 5
  ini.set [ kurenma ] command     = /usr/bin/update-firehol %IP%
  ini.set [ kurenma ] tcpflags    = syn

  ini.save $conf
  err::debug 2 && ini.show | sed -re "s/^[[:space:]]/\xc2\xa0\x20/"
  ini.free

  if [[ -d /run/systemd/system ]]; then

    systemctl stop  knockd.service
    sleep 2
    systemctl start knockd.service


  else

    service knockd stop
    sleep 2
    service knockd start

  fi

  std::finally "service down"

}
#
#
#
kurenma-setup-knockd::main
#
