#!/bin/bash
#
# $Id: setup-knockd 114 2016-10-21 16:12:24+04:00 toor $
#
_bashlyk=kurenma . bashlyk
#
#
#
#****h* command/setup-knockd
#
#  DESCRIPTION
#
#    part of the kurenma(7) package, tool to configure the third-party
#    application.
#    setup-knockd get knock-sequence  of  port  numbers  from  the  server's
#    X.509-certificate  and write the appropriate section of the settings in
#    the knockd.conf(5) configuration file. Only required for server roles.
#
#  SEE ALSO
#
#    update-firehol(8), knockd(1), gen-ssl-kurenma(8)
#
#******
udfMain() {

	udfExitIfAlreadyStarted

	[[ $UID == 0 ]] || eval $( udfOnError throw NotPermitted "You must be root to run this." )

	udfThrowOnCommandNotFound cat grep openssl sed

	local fmtKnockd fnCA iniKnockd pathIni s
	fmtKnockd="sequence=%d,%d,%d;seq_timeout=5;command=/usr/bin/update-firehol %%IP%%;tcpflags=syn"

	pathIni=$( _ pathIni )
	iniKnockd="/etc/knockd.conf"
	#
	fnCA=${pathIni}/ssl/public/cacert.pem

	[[ -s $fnCA ]] || eval $( udfOnError throw NoSuchFileOrDir $fnCA )

	#s=$(grep keyid $fnCA | sed -r -e "s/^.*keyid:(..):(..):(..):(..):(..):(..):.*$/0x\1\2 0x\3\4 0x\5\6/")
	s=$( openssl x509 -sha1 -in $fnCA -noout -fingerprint | sed -r -e "s/^SHA1 Fingerprint=(..):(..):(..):(..):(..):(..):.*$/0x\1\2 0x\3\4 0x\5\6/" )
	udfDebug 2 "keyid head: $s"
	s=$( printf -- "$fmtKnockd" $s )
	udfDebug 2 "  sequence: $s"

	udfIniChange $iniKnockd "$s" "kurenma"

	udfDebug 2 && cat $iniKnockd

	if systemctl >/dev/null 2>&1; then

		systemctl restart knockd.service

	else

		service knockd restart

	fi

	udfFinally "service down"

}
#
#
#
udfMain
#
